services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mtg-database'
      - 'POSTGRES_PASSWORD=mypass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    container_name: "mtg-database"
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: "mtg-redis"